#!/bin/bash
# Wrap memory-safety logs (Valgrind, ASan, UBSan) into a single HTML page.
#
# Usage: scripts/wrap_memory.sh <module_name> <reports_dir>
#   <module_name>  e.g. uds, pid, perception
#   <reports_dir>  e.g. reports/vv_uds
#
# Reads <reports_dir>/memory_safety/*.log and writes
# <reports_dir>/memory_html/index.html.

set -eu

MODULE="${1:?module name required}"
REPORTS="${2:?reports dir required}"
SRC="$REPORTS/memory_safety"
OUT="$REPORTS/memory_html"

mkdir -p "$OUT"

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')

# Helper: render a log file in a styled <pre>, mark "(clean)" when empty.
render_log() {
    local path="$1"
    local label="$2"
    if [ ! -f "$path" ]; then
        echo "<p><em>${label}: log not produced.</em></p>"
        return
    fi
    if [ ! -s "$path" ]; then
        echo "<p class=\"ok\">${label}: <strong>clean</strong> (no errors)</p>"
        return
    fi
    echo "<h3>${label}</h3>"
    echo "<pre>"
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$path"
    echo "</pre>"
}

cat > "$OUT/index.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${MODULE^^} — Memory Safety Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 1100px; margin: 2em auto; padding: 0 1em; color: #222; }
  h1 { color: #1a3a5c; border-bottom: 3px solid #1a3a5c; padding-bottom: 0.3em; }
  h2 { color: #2c5f8a; margin-top: 1.5em; }
  h3 { color: #444; margin-top: 1em; }
  pre { background: #f4f4f4; border: 1px solid #ddd; padding: 1em;
        overflow-x: auto; font-size: 0.85em; line-height: 1.4; }
  .meta { color: #666; font-size: 0.9em; }
  .ok { color: #1b5e20; font-weight: bold; }
  .nav { margin-bottom: 2em; }
  .nav a { color: #2c5f8a; text-decoration: none; margin-right: 1em; }
  .nav a:hover { text-decoration: underline; }
</style>
</head>
<body>
<div class="nav">
  <a href="../">↑ Module reports</a> ·
  <a href="../../../">↑ All modules</a>
</div>

<h1>${MODULE^^} — Memory Safety Report</h1>
<p class="meta">Commit <code>${COMMIT}</code> · Generated ${DATE}</p>

<p>This report aggregates the dynamic analysis results for the
<code>${MODULE}</code> module: Valgrind (memory leaks, invalid access),
AddressSanitizer (heap/stack corruption), and UndefinedBehaviorSanitizer
(signed overflow, invalid shifts, etc.).</p>

<h2>Valgrind</h2>
$(render_log "$SRC/valgrind_test_${MODULE}.log"       "Nominal suite")
$(render_log "$SRC/valgrind_test_${MODULE}_fault.log" "Fault-injection suite")

<h2>UndefinedBehaviorSanitizer</h2>
$(render_log "$SRC/ubsan_test_${MODULE}.log"       "Nominal suite")
$(render_log "$SRC/ubsan_test_${MODULE}_fault.log" "Fault-injection suite")

<hr>
<p class="meta">Generated by GitHub Actions ·
  <a href="https://github.com/erycaaf/AEB-stellantis-project">Repository</a></p>
</body>
</html>
HTML

echo "Memory-safety HTML written to $OUT/index.html"
