#!/usr/bin/env python3
"""Wrap fault-injection log into an HTML table with pass/fail per assertion.

Usage: scripts/wrap_fault.py <module_name> <reports_dir>
  <module_name>  e.g. uds, pid, perception
  <reports_dir>  e.g. reports/vv_uds

Reads <reports_dir>/fault_injection/run.log and writes
<reports_dir>/fault_html/index.html.

The expected log format is:
  [01] test_name_here                                   PASS
  [02] test_other_name                                  FAIL
  ...
  Results: N / M passed
"""

import html
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def git_short_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            text=True, stderr=subprocess.DEVNULL).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def parse_log(log_text: str) -> tuple[list[tuple[str, str, str]], str]:
    """Return list of (number, name, status) and the summary line."""
    rows = re.findall(r"\[(\d+)\]\s+(\S+).*?(PASS|FAIL)", log_text)
    summary_match = re.search(r"Results:\s*(\d+\s*/\s*\d+\s*passed)", log_text)
    summary = summary_match.group(1) if summary_match else "no summary"
    return rows, summary


def render_html(module: str, rows: list[tuple[str, str, str]],
                summary: str, sha: str, log_text: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pass_count = sum(1 for _, _, s in rows if s == "PASS")
    fail_count = sum(1 for _, _, s in rows if s == "FAIL")

    table_rows = []
    for n, name, status in rows:
        klass = "ok" if status == "PASS" else "err"
        table_rows.append(
            f'<tr><td class="num">{n}</td>'
            f'<td><code>{html.escape(name)}</code></td>'
            f'<td class="{klass}">{status}</td></tr>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{module.upper()} — Fault Injection Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 1100px; margin: 2em auto; padding: 0 1em; color: #222; }}
  h1 {{ color: #1a3a5c; border-bottom: 3px solid #1a3a5c; padding-bottom: 0.3em; }}
  h2 {{ color: #2c5f8a; margin-top: 1.5em; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1em; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }}
  th {{ background: #1a3a5c; color: white; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  td.num {{ width: 50px; color: #666; font-family: monospace; }}
  td.ok {{ color: #1b5e20; font-weight: bold; }}
  td.err {{ color: #b71c1c; font-weight: bold; }}
  .meta {{ color: #666; font-size: 0.9em; }}
  .summary {{ background: #e8f5e9; border-left: 4px solid #1b5e20;
             padding: 1em; margin: 1em 0; }}
  .summary.partial {{ background: #fff3e0; border-left-color: #e65100; }}
  pre {{ background: #f4f4f4; border: 1px solid #ddd; padding: 1em;
        overflow-x: auto; font-size: 0.8em; }}
  details {{ margin-top: 2em; }}
  .nav {{ margin-bottom: 2em; }}
  .nav a {{ color: #2c5f8a; text-decoration: none; margin-right: 1em; }}
  .nav a:hover {{ text-decoration: underline; }}
</style>
</head>
<body>
<div class="nav">
  <a href="../">↑ Module reports</a> ·
  <a href="../../../">↑ All modules</a>
</div>

<h1>{module.upper()} — Fault Injection Report</h1>
<p class="meta">Commit <code>{sha}</code> · Generated {timestamp}</p>

<div class="summary{' partial' if fail_count else ''}">
  <strong>Result:</strong> {summary} ·
  {pass_count} passed · {fail_count} failed
</div>

<h2>Per-assertion results</h2>
<table>
  <tr><th>#</th><th>Test</th><th>Status</th></tr>
  {''.join(table_rows)}
</table>

<details>
<summary>Raw log</summary>
<pre>{html.escape(log_text)}</pre>
</details>

<hr>
<p class="meta">Generated by GitHub Actions ·
  <a href="https://github.com/erycaaf/AEB-stellantis-project">Repository</a></p>
</body>
</html>
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    module = sys.argv[1]
    reports_dir = Path(sys.argv[2])
    log_path = reports_dir / "fault_injection" / "run.log"
    out_dir = reports_dir / "fault_html"
    out_path = out_dir / "index.html"

    out_dir.mkdir(parents=True, exist_ok=True)

    if not log_path.exists():
        print(f"WARNING: {log_path} not found; writing empty report",
              file=sys.stderr)
        log_text = "(log not produced)"
    else:
        log_text = log_path.read_text()

    rows, summary = parse_log(log_text)
    html_text = render_html(module, rows, summary, git_short_sha(), log_text)
    out_path.write_text(html_text)
    print(f"Fault-injection HTML written to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
